---
- name: Package pre-requisites
  apt: name={{ item }} state=latest
  with_items:
    - git
    - imagemagick
    - ruby-openid
    - ruby
    - build-essential
    - ruby-dev
    - libmysqlclient-dev
    - libpq-dev
    - libmagickwand-dev
    - libsqlite3-dev

- name: Create redmine user account
  user: name="{{ redmine_user }}" home="{{ redmine_path }}" createhome=no system=yes

- name: Create redmine directory
  file: path="{{ redmine_path }}" owner="{{ redmine_user }}" group="{{ redmine_user }}" state=directory

- name: Clone repository
  git: repo=https://github.com/redmine/redmine.git dest="{{ redmine_path }}" version='{{ redmine_version }}' accept_hostkey=yes
  sudo: yes
  sudo_user: "{{ redmine_user }}"

- name: Ensure Puma will be installed
  lineinfile: dest="{{ redmine_path }}/Gemfile" line='gem "puma"'

- include: install.yml
  when: not redmine_update

- include: update.yml
  when: redmine_update

- name: Clean up [1/2]
  shell: bundle exec rake tmp:cache:clear
  args:
    chdir: "{{ redmine_path }}"
  sudo: yes
  sudo_user: "{{ redmine_user }}"

- name: Clean up [2/2]
  shell: bundle exec rake tmp:sessions:clear
  args:
    chdir: "{{ redmine_path }}"
  sudo: yes
  sudo_user: "{{ redmine_user }}"
