---

- name: Backup database
  shell: >
    sudo -u "{{redmine_user }}" pg_dump
    {% if redmine_db_host %}-h {{ redmine_db_host }}{% endif %}
    {{ redmine_db_name }} > "/root/redmine-update-{{ redmine_version }}-{{ ansible_date_time.iso8601 }}.sql"

- name: Update Dependencies
  shell: bundle update
  args:
    chdir: "{{ redmine_path }}"
  sudo: yes
  sudo_user: "{{ redmine_user }}"

- name: Migrate database
  shell: RAILS_ENV=production bundle exec rake db:migrate
  args:
    chdir: "{{ redmine_path }}"
  sudo: yes
  sudo_user: "{{ redmine_user }}"

- name: Migrate plugins
  shell: RAILS_ENV=production bundle exec rake redmine:plugins:migrate
  args:
    chdir: "{{ redmine_path }}"
  sudo: yes
  sudo_user: "{{ redmine_user }}"
